version: "3"
services:
  host:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: host
    volumes:
      - .:/build

  node1:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    volumes:
      - .:/build

  node2:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    volumes:
      - .:/build

  node3:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    volumes:
      - .:/build

  node4:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node4
    volumes:
      - .:/build
